/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TranscribingRouteImport } from './routes/transcribing'
import { Route as RecordingRouteImport } from './routes/recording'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NotificationRouteImport } from './routes/notification'
import { Route as dashboardIndexRouteImport } from './routes/(dashboard)/index'
import { Route as dashboardSettingsRouteImport } from './routes/(dashboard)/settings'
import { Route as dashboardModelsRouteImport } from './routes/(dashboard)/models'

const TranscribingRoute = TranscribingRouteImport.update({
  id: '/transcribing',
  path: '/transcribing',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordingRoute = RecordingRouteImport.update({
  id: '/recording',
  path: '/recording',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationRoute = NotificationRouteImport.update({
  id: '/notification',
  path: '/notification',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardIndexRoute = dashboardIndexRouteImport.update({
  id: '/(dashboard)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardSettingsRoute = dashboardSettingsRouteImport.update({
  id: '/(dashboard)/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardModelsRoute = dashboardModelsRouteImport.update({
  id: '/(dashboard)/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/notification': typeof NotificationRoute
  '/onboarding': typeof OnboardingRoute
  '/recording': typeof RecordingRoute
  '/transcribing': typeof TranscribingRoute
  '/models': typeof dashboardModelsRoute
  '/settings': typeof dashboardSettingsRoute
  '/': typeof dashboardIndexRoute
}
export interface FileRoutesByTo {
  '/notification': typeof NotificationRoute
  '/onboarding': typeof OnboardingRoute
  '/recording': typeof RecordingRoute
  '/transcribing': typeof TranscribingRoute
  '/models': typeof dashboardModelsRoute
  '/settings': typeof dashboardSettingsRoute
  '/': typeof dashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/notification': typeof NotificationRoute
  '/onboarding': typeof OnboardingRoute
  '/recording': typeof RecordingRoute
  '/transcribing': typeof TranscribingRoute
  '/(dashboard)/models': typeof dashboardModelsRoute
  '/(dashboard)/settings': typeof dashboardSettingsRoute
  '/(dashboard)/': typeof dashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/notification'
    | '/onboarding'
    | '/recording'
    | '/transcribing'
    | '/models'
    | '/settings'
    | '/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/notification'
    | '/onboarding'
    | '/recording'
    | '/transcribing'
    | '/models'
    | '/settings'
    | '/'
  id:
    | '__root__'
    | '/notification'
    | '/onboarding'
    | '/recording'
    | '/transcribing'
    | '/(dashboard)/models'
    | '/(dashboard)/settings'
    | '/(dashboard)/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  NotificationRoute: typeof NotificationRoute
  OnboardingRoute: typeof OnboardingRoute
  RecordingRoute: typeof RecordingRoute
  TranscribingRoute: typeof TranscribingRoute
  dashboardModelsRoute: typeof dashboardModelsRoute
  dashboardSettingsRoute: typeof dashboardSettingsRoute
  dashboardIndexRoute: typeof dashboardIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transcribing': {
      id: '/transcribing'
      path: '/transcribing'
      fullPath: '/transcribing'
      preLoaderRoute: typeof TranscribingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recording': {
      id: '/recording'
      path: '/recording'
      fullPath: '/recording'
      preLoaderRoute: typeof RecordingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notification': {
      id: '/notification'
      path: '/notification'
      fullPath: '/notification'
      preLoaderRoute: typeof NotificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/': {
      id: '/(dashboard)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof dashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/settings': {
      id: '/(dashboard)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof dashboardSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/models': {
      id: '/(dashboard)/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof dashboardModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  NotificationRoute: NotificationRoute,
  OnboardingRoute: OnboardingRoute,
  RecordingRoute: RecordingRoute,
  TranscribingRoute: TranscribingRoute,
  dashboardModelsRoute: dashboardModelsRoute,
  dashboardSettingsRoute: dashboardSettingsRoute,
  dashboardIndexRoute: dashboardIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
